name: main

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "*"
  pull_request:
    branches:
      - "master"
    types: [ opened, synchronize ]

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: lint
        # Run ./gradlew spotlessApply when failing on this step.
        run: ./gradlew spotlessCheck
      - run: ./gradlew test
      - name: Show Current Version
        run: ./gradlew printVersion
      - name: Build Gem & Put it into './build/gems/' Directory
        run: ./gradlew gem
      - name: Set up JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby
      - name: push gem
        uses: trocco-io/push-gem-to-gpr-action@v1
        with:
          language: java
          gem-path: "./pkg/*.gem"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
