name: main

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  pull_request:
    branches:
      - "master"
    types: [ opened, synchronize ]
  pull_request_target:
    branches:
      - "master"
    types: [labeled]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event_name == 'pull_request' ||
        (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test')) ||
        startsWith(github.ref, 'refs/tags/')
      }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Lint
        run: ./gradlew spotlessCheck
      - name: Test
        run: ./gradlew test
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [ test ]
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: push gem
        uses: trocco-io/push-gem-to-gpr-action@v1
        with:
          language: java
          gem-path: "./build/gems/*.gem"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
